build:
  env:
    PYTHON_VERSION: "3.11.8"
  packages:
    - python3-pip
    - python3-dev
    - build-essential
  steps:
    - pip install --upgrade pip
    - pip install -r requirements-minimal.txt 