name: Daily Commit Workflow

on:
  schedule:
    # Run at 10:30 AM UTC every day
    - cron: '30 10 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  create-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '24f2000935@ds.study.iitm.ac.in'

      - name: Create commit with timestamp
        run: |
          echo "Last updated: $(date)" > timestamp.txt
          git add timestamp.txt
          git commit -m "Update timestamp [skip ci]"
          git push origin HEAD:${{ github.ref }} 